"""Conversation states for ACPF Bot."""

# Conversation states
LANGUAGE_SELECT = 0
POSITIONING = 1
Q1 = 2
Q2 = 3
Q3 = 4
READINESS = 5
REVIEW_ANSWERS = 6
RECOMMENDATION = 7
GATE_QUESTION = 8
UPSELL_TEAM = 9
UPSELL_INTENT = 10
REG_NAME = 11
REG_PHONE = 12
REG_EMAIL = 13
REG_BUSINESS = 14
CONFIRMATION = 15
EDIT_FORM_MENU = 16
EDIT_NAME = 17
EDIT_PHONE = 18
EDIT_EMAIL = 19
EDIT_BUSINESS = 20
