"""Conversation states for ACPF Bot."""

# Conversation states
LANGUAGE_SELECT = 0
POSITIONING = 1
Q1 = 2
Q2 = 3
Q3 = 4
READINESS = 5
RECOMMENDATION = 6
GATE_QUESTION = 7
UPSELL_TEAM = 8
UPSELL_INTENT = 9
REG_NAME = 10
REG_PHONE = 11
REG_EMAIL = 12
REG_BUSINESS = 13
CONFIRMATION = 14
